project:
  type: website

website:
  title: "Teste_Alelo"
  navbar:
    left:
      - href: index.qmd
        text: Apresentação
      - cleaning.qmd
      - clustering.qmd
      - classification.qmd
      - regression.qmd
      - bonus.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

